#!/bin/sh

# script/builds - builds the release

# exit on sub-module failure
set -e

cd "$(dirname "$0")/.."

# ------

echo "Publishing Docker Hub..."

docker build -t aspnetcore-circleci-azure .
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
docker tag aspnetcore-circleci-azure $DOCKER_USER/aspnetcore-circleci-azure:latest
docker push $DOCKER_USER/aspnetcore-circleci-azure

echo "Done publishing!"

# ------
